### ISSUE TITLE
Board Covering some of hand

### ISSUE THREAD

**Issue by SoulSorcerers** [SoulSorcerers/SoulSorcerers#3]
Some people are having issues since they are using a different resolution to myself.  This is causing the board to overlap the hand, thus, making the cost and minion name un-readable.  I will fix this as soon as I see some evidence of which container is causing this issue by lowering the alpha

**Comment by sasfog** [comment]
![minion_played](https://cloud.githubusercontent.com/assets/9408790/22173849/cc30f044-dfce-11e6-9aa6-7a9999a67f90.png)
![submit_attackers](https://cloud.githubusercontent.com/assets/9408790/22173850/d272baf0-dfce-11e6-81f0-172d7984613b.png)
